#!/bin/sh

set -eux

sudo bash -c "wget -qO - https://scribe.network/ppa/KEY.gpg | apt-key add - " && \
sudo bash -c "wget -qO - https://scribe.network/ppa/ubuntu/xenial/scribe.list > /etc/apt/sources.list.d/scribe.list " && \
sudo bash -c "apt update -qq " && \
sudo bash -c "apt install -y scribe "
